sudo: required

services:
  - docker

language: generic

env:
  global:
    - NAME=redis
    - IMAGE=kubernetesmailserver/${NAME}
    - NAMESPACE=mail-server
    - REPLICAS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_fe856b226a4b_key -iv $encrypted_fe856b226a4b_iv -in kubeconfig.enc -out kubeconfig -d
  - KUBE_LATEST_VERSION="v1.14.1"
  - HELM_LATEST_VERSION="v2.13.1"
  - HELM=https://storage.googleapis.com/kubernetes-helm/helm-${HELM_LATEST_VERSION}-linux-amd64.tar.gz
  - KUBECTL=https://storage.googleapis.com/kubernetes-release/release/${KUBE_LATEST_VERSION}/bin/linux/amd64/kubectl
  - curl -L ${KUBECTL} -o $PWD/kubectl
  - curl -L ${HELM} | tar xzO linux-amd64/helm > $PWD/helm
  - chmod +x $PWD/helm $PWD/kubectl
  - export -p PATH=$PATH:$PWD

jobs:
  include:
    - stage: deploy
      name: Deploy the master branch to the kubernetes cluster
      if: branch = master and type != pull_request
      script:
        - export KUBECONFIG=$PWD/kubeconfig
        - kubectl get pods
        - kubectl scale --replicas=0 deployment/${NAME} || true
        - kubectl get deployments
        - helm template
            --set name=${NAME}
            --set namespace=${NAMESPACE}
            --set port=$(kubectl get cm services-info -o=jsonpath="{.data.REDIS_PORT}")
            $PWD/kubernetes | kubectl apply -f -
        - kubectl scale --replicas=${REPLICAS} deployment/${NAME}
        - kubectl get deployments
