apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.namespace }}
        role: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: redis:alpine
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: services-info
          ports:
            - name: {{ .Values.name }}
              containerPort: {{ .Values.port }}
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.namespace }}
    role: {{ .Values.name }}
  ports:
    - name: {{ .Values.name }}
      port: {{ .Values.redis_port }}
      targetPort: {{ .Values.port }}
